<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Etapa 2 e 3</title>

<script src="site_libs/header-attrs-2.4.6/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<script src="site_libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="site_libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="site_libs/anchor-sections-1.0/anchor-sections.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

.sourceCode .row {
  width: 100%;
}
.sourceCode {
  overflow-x: auto;
}
.code-folding-btn {
  margin-right: -30px;
}
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">DS</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="etapa1_eda.html">Etapa 1</a>
</li>
<li>
  <a href="etapa2_3.html">Etapa 2 e 3</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Etapa 2 e 3</h1>

</div>


<p>As etapas 2 e 3 foram destinadas para modelagem e o problema escolhido foi o de predizer o desempenho dos estudantes nas avaliações finais. Além disso, o candidato deve avaliar a qualidade e precisão do modelo.</p>
<p>Algumas ressalvas precisam ser feitas em relação a task pedida, a documentação da OU (Open University) e a integridade dos dados.</p>
<p>As avaliações finais no dataset correspondem a classe <em>“Exam”</em>, presente na variável <code>assessment_type</code>. No entanto, possuímos muitos valores missing nesta variável e sua importância para composição da nota final é muitas vezes dúbia. Isso por que encontramos estudantes que pontuaram 0 no <code>Exam</code> e ainda assim foram aprovados, assim como estudantes que não fizeram o teste e foram aprovados.</p>
<p>Isso por que as avaliações finais servem para compor sua nota final, valor esse que de fato vai indicar se o estudante foi aprovado ou não no curso. E essa composição não é dita na documentação dos dados, e é pouco provável de ser encontrada apenas pela análise dos dados atuais.</p>
<p>Tem mais um ponto que precisa ser comentado, ao pensar em utilizar as notas individuais em cada avaliação encontrei outro problema. Alguns cursos zeraram os pesos de cada teste, gerando assim mais incosistências em relação a correlação de quem foi aprovado ou não e seu desempenho.</p>
<div id="libs" class="section level1">
<h1>Libs</h1>
<p>Abaixo você encontra os pacotes utilizados para esta etapa do case.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="kw">library</span>(skimr)</span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="kw">library</span>(data.table)</span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="kw">library</span>(tidytable)</span>
<span id="cb1-5"><a href="#cb1-5"></a><span class="kw">library</span>(data.table)</span>
<span id="cb1-6"><a href="#cb1-6"></a><span class="kw">library</span>(lubridate)</span>
<span id="cb1-7"><a href="#cb1-7"></a><span class="kw">library</span>(tidytext)</span>
<span id="cb1-8"><a href="#cb1-8"></a><span class="kw">library</span>(ggridges)</span>
<span id="cb1-9"><a href="#cb1-9"></a><span class="kw">library</span>(sf)</span>
<span id="cb1-10"><a href="#cb1-10"></a><span class="kw">library</span>(geofacet)</span>
<span id="cb1-11"><a href="#cb1-11"></a><span class="kw">library</span>(rlang)</span>
<span id="cb1-12"><a href="#cb1-12"></a><span class="kw">library</span>(plotly)</span></code></pre></div>
</div>
<div id="procedimento-adotado" class="section level1">
<h1>Procedimento adotado</h1>
<p>Diante ao que dito, o procedimento adotado aqui foi o de retirar os valores missings da variável <code>assessment_type</code> e trabalhar com as informações que sobrarem. Sendo que essa é nossa variável target, não faria sentido utilizar nenhum método de imputação nela.</p>
<p>Para obter o dataset para modelagem precisamos realizar uma série de joins entre as tableas disponíveis, para que cada observação dos dados fosse composta por um estudante de um determinado período e curso diferente.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># obtendo o dataset para modelagem</span></span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="co"># primeira parte: dados apenas sobre as avaliações finais (Exam) </span></span>
<span id="cb2-3"><a href="#cb2-3"></a>final_score_exam_tbl &lt;-<span class="st"> </span>student_info <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb2-4"><a href="#cb2-4"></a><span class="st">  </span><span class="co"># coletando pesos e ids das avaliações </span></span>
<span id="cb2-5"><a href="#cb2-5"></a><span class="st">  </span><span class="kw">left_join</span>(assessments, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;code_module&quot;</span>, <span class="st">&quot;code_presentation&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb2-6"><a href="#cb2-6"></a><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>gender<span class="op">:-</span>disability, <span class="op">-</span>date) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb2-7"><a href="#cb2-7"></a><span class="st">  </span><span class="co"># coletando as notas individuais dos estudantes</span></span>
<span id="cb2-8"><a href="#cb2-8"></a><span class="st">  </span><span class="kw">left_join</span>(student_assessment, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;id_student&quot;</span>, <span class="st">&quot;id_assessment&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb2-9"><a href="#cb2-9"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">weighted =</span> (weight<span class="op">/</span><span class="dv">100</span>) <span class="op">*</span><span class="st"> </span>score) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb2-10"><a href="#cb2-10"></a><span class="st">  </span><span class="kw">filter</span>(assessment_type <span class="op">==</span><span class="st"> &quot;Exam&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb2-11"><a href="#cb2-11"></a><span class="st">  </span><span class="kw">drop_na</span>(score) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb2-12"><a href="#cb2-12"></a><span class="st">  </span><span class="kw">group_by</span>(code_module, code_presentation, id_student, final_result) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb2-13"><a href="#cb2-13"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">final_score_exam =</span> <span class="kw">sum</span>(weighted)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb2-14"><a href="#cb2-14"></a><span class="st">  </span><span class="kw">ungroup</span>()</span></code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;code_module&#39;, &#39;code_presentation&#39;, &#39;id_student&#39; (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="co"># segunda parte: join dos dados sobre as avaliações finais com o dataset base (student_info)</span></span>
<span id="cb4-2"><a href="#cb4-2"></a>exam_info_tbl &lt;-<span class="st"> </span>student_info <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb4-3"><a href="#cb4-3"></a><span class="st">  </span><span class="kw">left_join</span>(final_score_exam_tbl, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;code_module&quot;</span>, <span class="st">&quot;code_presentation&quot;</span>, <span class="st">&quot;id_student&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb4-4"><a href="#cb4-4"></a><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>final_result.y) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb4-5"><a href="#cb4-5"></a><span class="st">  </span><span class="kw">rename</span>(<span class="dt">final_result =</span> final_result.x) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb4-6"><a href="#cb4-6"></a><span class="st">  </span><span class="kw">drop_na</span>(final_score_exam)</span></code></pre></div>
<p>Algumas variáveis não fazem sentido serem adicionadas para treino do modelo, pois não são informações previamente disponíveis para cada estudante, ou seja, elas aconteceram apenas no futuro e portanto não tem como serem usadas como preditoras. Por conta disso, iremos dropar algumas features.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>exam_info_v2_tbl &lt;-<span class="st"> </span>exam_info_tbl <span class="op">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2"></a><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>studied_credits, <span class="op">-</span>final_result)</span></code></pre></div>
<p>Meu intuito inicial era realizar a previsão do desempenho por curso, porém, como temos poucos dados fica inviável tão abordagem.</p>
<p>Como nosso dataset é predominante categórico, é super interessante observar como está a distribuição das diferentes classes. Para isso eu criei uma função que nos permite visualizar todas as features com apenas um comando.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>plot_all_full_data &lt;-<span class="st"> </span><span class="cf">function</span>(<span class="dt">name =</span> <span class="st">&quot;region&quot;</span>) {</span>
<span id="cb6-2"><a href="#cb6-2"></a>  </span>
<span id="cb6-3"><a href="#cb6-3"></a>  exam_info_v2_tbl <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb6-4"><a href="#cb6-4"></a><span class="st">    </span><span class="kw">count</span>(.data[[name]]) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb6-5"><a href="#cb6-5"></a><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">prop =</span> n<span class="op">/</span><span class="kw">sum</span>(n)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb6-6"><a href="#cb6-6"></a><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> <span class="kw">fct_reorder</span>(.data[[name]], prop),</span>
<span id="cb6-7"><a href="#cb6-7"></a>               <span class="dt">x =</span> prop)) <span class="op">+</span></span>
<span id="cb6-8"><a href="#cb6-8"></a><span class="st">    </span><span class="kw">geom_col</span>()</span>
<span id="cb6-9"><a href="#cb6-9"></a>}</span>
<span id="cb6-10"><a href="#cb6-10"></a></span>
<span id="cb6-11"><a href="#cb6-11"></a></span>
<span id="cb6-12"><a href="#cb6-12"></a>names &lt;-<span class="st"> </span><span class="kw">names</span>(exam_info_v2_tbl <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="kw">where</span>(is.character)))</span>
<span id="cb6-13"><a href="#cb6-13"></a>all_plots &lt;-<span class="st"> </span><span class="kw">map</span>(names, <span class="dt">.f =</span> plot_all)</span>
<span id="cb6-14"><a href="#cb6-14"></a>cowplot<span class="op">::</span><span class="kw">plot_grid</span>(<span class="dt">plotlist =</span> all_plots)</span></code></pre></div>
<p><img src="etapa2_3_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Vimos aqui que algumas classes são bem desiquilibradas e isso pode ser um problema para nossa previsão. Por enquanto seguiremos desta forma para criação de um modelo baseline.</p>
<p>Além disso, a variável <code>imd_band</code> possui alguns valores missing. Por enquanto a mesma não será considerada.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>exam_info_final_tbl &lt;-<span class="st"> </span>exam_info_v2_tbl <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="op">-</span>imd_band)</span></code></pre></div>
<p>Sendo assim, nosso dataset que será utilizado para as previsões é o <code>exam_info_final_tbl</code>.</p>
</div>
<div id="split-de-treino-e-teste" class="section level1">
<h1>Split de treino e teste</h1>
<p>Precisamos dividir nossos dados entre treino e teste. Um problema que pode ocorrer aqui é das classes ficarem com distribuições diferentes, ou ainda classes de pouca ocorrência ficarem fora de algum conjunto de dado. A função <code>initial_split()</code> possui uma forma de auxiliar nessa tarefa, o parâmetro <code>strata</code>, este serve para indicar qual variável irá manter a proporção de classes na hora do split.</p>
<p>Nesse caso eu optei pela variável <code>highest_education</code> por conter algumas classes com pouquísimos valores.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>splits &lt;-<span class="st"> </span><span class="kw">initial_split</span>(<span class="dt">prop =</span> <span class="fl">.7</span>, <span class="dt">strata =</span> <span class="st">&quot;highest_education&quot;</span>, <span class="dt">data =</span> exam_info_final_tbl)</span>
<span id="cb8-2"><a href="#cb8-2"></a></span>
<span id="cb8-3"><a href="#cb8-3"></a>train &lt;-<span class="st"> </span><span class="kw">training</span>(splits)</span>
<span id="cb8-4"><a href="#cb8-4"></a>test &lt;-<span class="st"> </span><span class="kw">testing</span>(splits)</span></code></pre></div>
<p>Vamos checar novamente as distribuições.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a>plot_all_full_train &lt;-<span class="st"> </span><span class="cf">function</span>(<span class="dt">name =</span> <span class="st">&quot;region&quot;</span>) {</span>
<span id="cb9-2"><a href="#cb9-2"></a>  </span>
<span id="cb9-3"><a href="#cb9-3"></a>  train <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb9-4"><a href="#cb9-4"></a><span class="st">    </span><span class="kw">count</span>(.data[[name]]) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb9-5"><a href="#cb9-5"></a><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">prop =</span> n<span class="op">/</span><span class="kw">sum</span>(n)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb9-6"><a href="#cb9-6"></a><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> <span class="kw">fct_reorder</span>(.data[[name]], prop),</span>
<span id="cb9-7"><a href="#cb9-7"></a>               <span class="dt">x =</span> prop)) <span class="op">+</span></span>
<span id="cb9-8"><a href="#cb9-8"></a><span class="st">    </span><span class="kw">geom_col</span>()</span>
<span id="cb9-9"><a href="#cb9-9"></a>}</span>
<span id="cb9-10"><a href="#cb9-10"></a></span>
<span id="cb9-11"><a href="#cb9-11"></a>names &lt;-<span class="st"> </span><span class="kw">names</span>(train <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="kw">where</span>(is.character)))</span>
<span id="cb9-12"><a href="#cb9-12"></a>all_plots &lt;-<span class="st"> </span><span class="kw">map</span>(names, plot_all_full_train)</span>
<span id="cb9-13"><a href="#cb9-13"></a>cowplot<span class="op">::</span><span class="kw">plot_grid</span>(<span class="dt">plotlist =</span> all_plots)</span></code></pre></div>
<p><img src="etapa2_3_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>plot_all_full_test &lt;-<span class="st"> </span><span class="cf">function</span>(<span class="dt">name =</span> <span class="st">&quot;region&quot;</span>) {</span>
<span id="cb10-2"><a href="#cb10-2"></a>  </span>
<span id="cb10-3"><a href="#cb10-3"></a>  test <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb10-4"><a href="#cb10-4"></a><span class="st">    </span><span class="kw">count</span>(.data[[name]]) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb10-5"><a href="#cb10-5"></a><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">prop =</span> n<span class="op">/</span><span class="kw">sum</span>(n)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb10-6"><a href="#cb10-6"></a><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> <span class="kw">fct_reorder</span>(.data[[name]], prop),</span>
<span id="cb10-7"><a href="#cb10-7"></a>               <span class="dt">x =</span> prop)) <span class="op">+</span></span>
<span id="cb10-8"><a href="#cb10-8"></a><span class="st">    </span><span class="kw">geom_col</span>()</span>
<span id="cb10-9"><a href="#cb10-9"></a>}</span>
<span id="cb10-10"><a href="#cb10-10"></a></span>
<span id="cb10-11"><a href="#cb10-11"></a>names &lt;-<span class="st"> </span><span class="kw">names</span>(test <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="kw">where</span>(is.character)))</span>
<span id="cb10-12"><a href="#cb10-12"></a>all_plots &lt;-<span class="st"> </span><span class="kw">map</span>(names, plot_all_full_test)</span>
<span id="cb10-13"><a href="#cb10-13"></a>cowplot<span class="op">::</span><span class="kw">plot_grid</span>(<span class="dt">plotlist =</span> all_plots)</span></code></pre></div>
<p><img src="etapa2_3_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a>student_final_result_tbl</span></code></pre></div>
<pre><code>## # A tibble: 31,482 x 11
##    code_module code_presentation id_student gender region          highest_education  imd_band age_band num_of_prev_attem… disability final_result
##    &lt;fct&gt;       &lt;fct&gt;                  &lt;dbl&gt; &lt;fct&gt;  &lt;fct&gt;           &lt;fct&gt;              &lt;ord&gt;    &lt;fct&gt;                 &lt;dbl&gt; &lt;fct&gt;      &lt;fct&gt;       
##  1 Curso A     2013J                  11391 M      East Anglian R… HE Qualification   90-100%  55&lt;=                      0 N          Pass        
##  2 Curso A     2013J                  28400 F      Scotland        HE Qualification   20-30%   35-55                     0 N          Pass        
##  3 Curso A     2013J                  30268 F      North Western … A Level or Equiva… 30-40%   35-55                     0 Y          Withdrawn   
##  4 Curso A     2013J                  31604 F      South East Reg… A Level or Equiva… 50-60%   35-55                     0 N          Pass        
##  5 Curso A     2013J                  32885 F      West Midlands … Lower Than A Level 50-60%   0-35                      0 N          Pass        
##  6 Curso A     2013J                  38053 M      Wales           A Level or Equiva… 80-90%   35-55                     0 N          Pass        
##  7 Curso A     2013J                  45462 M      Scotland        HE Qualification   30-40%   0-35                      0 N          Pass        
##  8 Curso A     2013J                  45642 F      North Western … A Level or Equiva… 90-100%  0-35                      0 N          Pass        
##  9 Curso A     2013J                  52130 F      East Anglian R… A Level or Equiva… 70-80%   0-35                      0 N          Pass        
## 10 Curso A     2013J                  57506 M      South Region    Lower Than A Level 70-80%   35-55                     0 N          Pass        
## # … with 31,472 more rows</code></pre>
<p>Visualizamos que em ambos os casos as proporções foram mantidas, o que é importante para generalização do modelo.</p>
</div>
<div id="recipe" class="section level1">
<h1>Recipe</h1>
<p>As etapas de pré-processamento serão feitas utilizando o pacote <code>recipes</code>. Onde cada step é responsável por uma transformação.</p>
<p>Optei por utilizar o one hot encoder em praticamente todas as variáveis categóricas, com excessão da <code>age_band</code> que é uma variável ordinal e pode apenas ser utilizada como fator.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a>recipe_spec &lt;-<span class="st"> </span><span class="kw">recipe</span>(final_score_exam <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> train) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb13-2"><a href="#cb13-2"></a><span class="st">  </span><span class="kw">update_role</span>(code_module, code_presentation, id_student, <span class="dt">new_role =</span> <span class="st">&quot;indicator&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3"></a><span class="st">  </span><span class="kw">step_string2factor</span>(age_band, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;0-35&quot;</span>, <span class="st">&quot;35-55&quot;</span>, <span class="st">&quot;55&lt;=&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb13-4"><a href="#cb13-4"></a><span class="st">  </span><span class="kw">step_dummy</span>(<span class="kw">all_predictors</span>(), <span class="op">-</span>num_of_prev_attempts, <span class="op">-</span>age_band, <span class="dt">one_hot =</span> T)</span>
<span id="cb13-5"><a href="#cb13-5"></a></span>
<span id="cb13-6"><a href="#cb13-6"></a></span>
<span id="cb13-7"><a href="#cb13-7"></a>recipe_spec <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">prep</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">juice</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 3,473
## Columns: 28
## $ code_module                                   &lt;fct&gt; Curso C, Curso C, Curso C, Curso C, Curso C, Curso C, Curso C, Curso C, Curso C, Curso C,…
## $ code_presentation                             &lt;fct&gt; 2014B, 2014B, 2014B, 2014B, 2014B, 2014B, 2014B, 2014B, 2014B, 2014B, 2014B, 2014B, 2014B…
## $ id_student                                    &lt;dbl&gt; 29764, 29820, 40604, 42638, 46605, 57340, 69703, 70381, 82575, 83219, 94484, 95906, 10552…
## $ age_band                                      &lt;fct&gt; 0-35, 0-35, 35-55, 35-55, 35-55, 0-35, 0-35, 35-55, 0-35, 0-35, 35-55, 0-35, 35-55, 0-35,…
## $ num_of_prev_attempts                          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ final_score_exam                              &lt;dbl&gt; 94, 76, 66, 50, 98, 68, 84, 90, 100, 82, 80, 82, 60, 52, 58, 24, 48, 100, 60, 86, 94, 48,…
## $ gender_F                                      &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,…
## $ gender_M                                      &lt;dbl&gt; 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,…
## $ region_East.Anglian.Region                    &lt;dbl&gt; 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,…
## $ region_East.Midlands.Region                   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,…
## $ region_Ireland                                &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ region_London.Region                          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ region_North.Region                           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,…
## $ region_North.Western.Region                   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,…
## $ region_Scotland                               &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ region_South.East.Region                      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ region_South.Region                           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,…
## $ region_South.West.Region                      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ region_Wales                                  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ region_West.Midlands.Region                   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,…
## $ region_Yorkshire.Region                       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ highest_education_A.Level.or.Equivalent       &lt;dbl&gt; 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,…
## $ highest_education_HE.Qualification            &lt;dbl&gt; 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,…
## $ highest_education_Lower.Than.A.Level          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ highest_education_No.Formal.quals             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ highest_education_Post.Graduate.Qualification &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ disability_N                                  &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
## $ disability_Y                                  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,…</code></pre>
<p>Explicação dos steps:</p>
<ul>
<li>update_role: cria uma especificação para algumas variáveis que não serão utilizadas como preditores mas terão um papel de identificação.</li>
<li>step_string2factor: conversão de variáveis categóricas para fator</li>
<li>step_dummy: aplicação do one-hot-encoding</li>
</ul>
</div>
<div id="model" class="section level1">
<h1>Model</h1>
<p>Na etapa anterior nós criamos especificações de pré-processamento, nessa nós criaremos especificações dos modelos.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="co"># 1 - Random Forest</span></span>
<span id="cb15-2"><a href="#cb15-2"></a>rf_spec &lt;-<span class="st"> </span><span class="kw">rand_forest</span>(<span class="dt">mode =</span> <span class="st">&quot;regression&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb15-3"><a href="#cb15-3"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;ranger&quot;</span>)</span>
<span id="cb15-4"><a href="#cb15-4"></a></span>
<span id="cb15-5"><a href="#cb15-5"></a><span class="co"># 2 - Linear Regression</span></span>
<span id="cb15-6"><a href="#cb15-6"></a>lm_spec &lt;-<span class="st"> </span><span class="kw">linear_reg</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb15-7"><a href="#cb15-7"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;lm&quot;</span>)</span></code></pre></div>
</div>
<div id="worflow" class="section level1">
<h1>Worflow</h1>
<p>No worflow você coloca tudo junto (modelo e receita).</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="co"># 1 - workflow random forest</span></span>
<span id="cb16-2"><a href="#cb16-2"></a>wf_rf_spec &lt;-<span class="st"> </span><span class="kw">workflow</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb16-3"><a href="#cb16-3"></a><span class="st">  </span><span class="kw">add_recipe</span>(recipe_spec) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb16-4"><a href="#cb16-4"></a><span class="st">  </span><span class="kw">add_model</span>(rf_spec)</span>
<span id="cb16-5"><a href="#cb16-5"></a></span>
<span id="cb16-6"><a href="#cb16-6"></a><span class="co"># 2 - workflow linear regression</span></span>
<span id="cb16-7"><a href="#cb16-7"></a>wf_lm_spec &lt;-<span class="st"> </span>wf_rf_spec <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">update_model</span>(lm_spec)</span></code></pre></div>
</div>
<div id="fit" class="section level1">
<h1>Fit</h1>
<p>No fit é onde de fato todas as especificações passadas são aplicadas e treinadas nos dados de treino.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a>fitted_rf_wf &lt;-<span class="st"> </span>wf_rf_spec <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb17-2"><a href="#cb17-2"></a><span class="st">  </span><span class="kw">fit</span>(<span class="dt">data =</span> train)</span>
<span id="cb17-3"><a href="#cb17-3"></a></span>
<span id="cb17-4"><a href="#cb17-4"></a>fitted_lm_wf &lt;-<span class="st"> </span>wf_lm_spec <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb17-5"><a href="#cb17-5"></a><span class="st">  </span><span class="kw">fit</span>(<span class="dt">data =</span> train)</span></code></pre></div>
</div>
<div id="predict" class="section level1">
<h1>Predict</h1>
<p>Aqui vamos realizar as previsões e salvar os resultados dos dois modelos em uma nova tabela.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a>results_treino &lt;-<span class="st"> </span>fitted_rf_wf <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb18-2"><a href="#cb18-2"></a><span class="st">  </span><span class="kw">predict</span>(<span class="dt">new_data =</span> train) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb18-3"><a href="#cb18-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">valor_real =</span> train<span class="op">$</span>final_score_exam,</span>
<span id="cb18-4"><a href="#cb18-4"></a>         <span class="dt">model =</span> <span class="st">&quot;rf&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb18-5"><a href="#cb18-5"></a><span class="st">  </span><span class="kw">bind_rows</span>(fitted_lm_wf <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb18-6"><a href="#cb18-6"></a><span class="st">              </span><span class="kw">predict</span>(<span class="dt">new_data =</span> train) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb18-7"><a href="#cb18-7"></a><span class="st">              </span><span class="kw">mutate</span>(<span class="dt">valor_real =</span> train<span class="op">$</span>final_score_exam,</span>
<span id="cb18-8"><a href="#cb18-8"></a>                     <span class="dt">model =</span> <span class="st">&quot;lm&quot;</span>))</span></code></pre></div>
<pre><code>## Warning in predict.lm(object = object$fit, newdata = new_data, type = &quot;response&quot;): prediction from a rank-deficient fit may be misleading</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a>results_test &lt;-<span class="st"> </span>fitted_rf_wf <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb20-2"><a href="#cb20-2"></a><span class="st">  </span><span class="kw">predict</span>(<span class="dt">new_data =</span> test) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb20-3"><a href="#cb20-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">valor_real =</span> test<span class="op">$</span>final_score_exam,</span>
<span id="cb20-4"><a href="#cb20-4"></a>         <span class="dt">model =</span> <span class="st">&quot;rf&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb20-5"><a href="#cb20-5"></a><span class="st">  </span><span class="kw">bind_rows</span>(fitted_lm_wf <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb20-6"><a href="#cb20-6"></a><span class="st">              </span><span class="kw">predict</span>(<span class="dt">new_data =</span> test) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb20-7"><a href="#cb20-7"></a><span class="st">              </span><span class="kw">mutate</span>(<span class="dt">valor_real =</span> test<span class="op">$</span>final_score_exam,</span>
<span id="cb20-8"><a href="#cb20-8"></a>                     <span class="dt">model =</span> <span class="st">&quot;lm&quot;</span>))</span></code></pre></div>
<pre><code>## Warning in predict.lm(object = object$fit, newdata = new_data, type = &quot;response&quot;): prediction from a rank-deficient fit may be misleading</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>results_test <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb22-2"><a href="#cb22-2"></a><span class="st">  </span><span class="kw">group_by</span>(model) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb22-3"><a href="#cb22-3"></a><span class="st">  </span><span class="kw">rmse</span>(valor_real, .pred)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   model .metric .estimator .estimate
##   &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 lm    rmse    standard        19.7
## 2 rf    rmse    standard        19.8</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a>results_treino <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb24-2"><a href="#cb24-2"></a><span class="st">  </span><span class="kw">group_by</span>(model) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb24-3"><a href="#cb24-3"></a><span class="st">  </span><span class="kw">rmse</span>(valor_real, .pred)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   model .metric .estimator .estimate
##   &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 lm    rmse    standard        19.9
## 2 rf    rmse    standard        19.2</code></pre>
<p>Vemos que os dois modelos possuem valores bem próximos do RMSE, quase 19.8 e 19.9. Podemos então visualizar os resíduos.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a>results_test <span class="op">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2"></a><span class="st">  </span><span class="co">#filter(model == &quot;rf&quot;) %&gt;% </span></span>
<span id="cb26-3"><a href="#cb26-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">task =</span> <span class="st">&quot;testing&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4"></a><span class="st">  </span><span class="kw">bind_rows</span>(results_treino <span class="op">%&gt;%</span></span>
<span id="cb26-5"><a href="#cb26-5"></a><span class="st">              </span><span class="kw">mutate</span>(<span class="dt">task =</span> <span class="st">&quot;training&quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb26-6"><a href="#cb26-6"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(valor_real, .pred, <span class="dt">color =</span> model)) <span class="op">+</span></span>
<span id="cb26-7"><a href="#cb26-7"></a><span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">color =</span> <span class="st">&quot;gray80&quot;</span>, <span class="dt">size =</span> <span class="fl">1.5</span>) <span class="op">+</span></span>
<span id="cb26-8"><a href="#cb26-8"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.5</span>) <span class="op">+</span></span>
<span id="cb26-9"><a href="#cb26-9"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>task) <span class="op">+</span></span>
<span id="cb26-10"><a href="#cb26-10"></a><span class="st">  </span><span class="kw">labs</span>(</span>
<span id="cb26-11"><a href="#cb26-11"></a>    <span class="dt">x =</span> <span class="st">&quot;Truth&quot;</span>,</span>
<span id="cb26-12"><a href="#cb26-12"></a>    <span class="dt">y =</span> <span class="st">&quot;Predicted attendance&quot;</span>,</span>
<span id="cb26-13"><a href="#cb26-13"></a>    <span class="dt">color =</span> <span class="st">&quot;Type of model&quot;</span></span>
<span id="cb26-14"><a href="#cb26-14"></a>  )</span></code></pre></div>
<p><img src="etapa2_3_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Pelo gráfico dos resíduos vemos que os dois modelos tiveram resultados bem próximos, tanto nos dados de treino quanto nos dados de teste. O ideal de um gráfico de resíduos é que esteja o mai próximo possível de uma linha reta, porém nossos resultados não foram muito bons.</p>
<p>Podemos aplicar uma técnica de resampling para investigar como o modelo se comporta em diferentes dados de validação.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a><span class="co"># apenas nos dados de treino</span></span>
<span id="cb27-2"><a href="#cb27-2"></a><span class="co"># mantendo a proporção do split inicial</span></span>
<span id="cb27-3"><a href="#cb27-3"></a><span class="kw">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb27-4"><a href="#cb27-4"></a>score_folds &lt;-<span class="st"> </span><span class="kw">vfold_cv</span>(train, <span class="dt">strata =</span> <span class="st">&quot;highest_education&quot;</span>, <span class="dt">v =</span> <span class="dv">5</span>)</span>
<span id="cb27-5"><a href="#cb27-5"></a></span>
<span id="cb27-6"><a href="#cb27-6"></a>rf_res &lt;-<span class="st"> </span><span class="kw">fit_resamples</span>(</span>
<span id="cb27-7"><a href="#cb27-7"></a>  wf_rf_spec,</span>
<span id="cb27-8"><a href="#cb27-8"></a>  score_folds,</span>
<span id="cb27-9"><a href="#cb27-9"></a>  <span class="dt">control =</span> <span class="kw">control_resamples</span>(<span class="dt">save_pred =</span> <span class="ot">TRUE</span>, <span class="dt">verbose =</span> T)</span>
<span id="cb27-10"><a href="#cb27-10"></a>)</span></code></pre></div>
<pre><code>## i Fold1: preprocessor 1/1</code></pre>
<pre><code>## ✓ Fold1: preprocessor 1/1</code></pre>
<pre><code>## i Fold1: preprocessor 1/1, model 1/1</code></pre>
<pre><code>## ✓ Fold1: preprocessor 1/1, model 1/1</code></pre>
<pre><code>## i Fold1: preprocessor 1/1, model 1/1 (predictions)</code></pre>
<pre><code>## i Fold2: preprocessor 1/1</code></pre>
<pre><code>## ✓ Fold2: preprocessor 1/1</code></pre>
<pre><code>## i Fold2: preprocessor 1/1, model 1/1</code></pre>
<pre><code>## ✓ Fold2: preprocessor 1/1, model 1/1</code></pre>
<pre><code>## i Fold2: preprocessor 1/1, model 1/1 (predictions)</code></pre>
<pre><code>## i Fold3: preprocessor 1/1</code></pre>
<pre><code>## ✓ Fold3: preprocessor 1/1</code></pre>
<pre><code>## i Fold3: preprocessor 1/1, model 1/1</code></pre>
<pre><code>## ✓ Fold3: preprocessor 1/1, model 1/1</code></pre>
<pre><code>## i Fold3: preprocessor 1/1, model 1/1 (predictions)</code></pre>
<pre><code>## i Fold4: preprocessor 1/1</code></pre>
<pre><code>## ✓ Fold4: preprocessor 1/1</code></pre>
<pre><code>## i Fold4: preprocessor 1/1, model 1/1</code></pre>
<pre><code>## ✓ Fold4: preprocessor 1/1, model 1/1</code></pre>
<pre><code>## i Fold4: preprocessor 1/1, model 1/1 (predictions)</code></pre>
<pre><code>## i Fold5: preprocessor 1/1</code></pre>
<pre><code>## ✓ Fold5: preprocessor 1/1</code></pre>
<pre><code>## i Fold5: preprocessor 1/1, model 1/1</code></pre>
<pre><code>## ✓ Fold5: preprocessor 1/1, model 1/1</code></pre>
<pre><code>## i Fold5: preprocessor 1/1, model 1/1 (predictions)</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1"></a>rf_res <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb53-2"><a href="#cb53-2"></a><span class="st">  </span><span class="kw">collect_metrics</span>()</span></code></pre></div>
<pre><code>## # A tibble: 2 x 6
##   .metric .estimator    mean     n std_err .config             
##   &lt;chr&gt;   &lt;chr&gt;        &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               
## 1 rmse    standard   20.1        5 0.115   Preprocessor1_Model1
## 2 rsq     standard    0.0487     5 0.00142 Preprocessor1_Model1</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1"></a><span class="co"># melhor modelo</span></span>
<span id="cb55-2"><a href="#cb55-2"></a>rf_res <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb55-3"><a href="#cb55-3"></a><span class="st">  </span><span class="kw">show_best</span>(<span class="dt">metric =</span> <span class="st">&quot;rmse&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 6
##   .metric .estimator  mean     n std_err .config             
##   &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               
## 1 rmse    standard    20.1     5   0.115 Preprocessor1_Model1</code></pre>
<p>O melhor RMSE considerando a média dos 5 conjuntos de dados de validação foi de 20.1, o que é um valor um pouco maior do que quando considerado apenas os dados de treino. A explicação é que na técnica de resampling você acaba reduzindo ainda mais os dados para ser possível treinar em uma parte e investigar a performance em outra, e como os dados já eram poucos fica mais difícil de capturar algum padrão nos dados.</p>
</div>
<div id="tunning" class="section level1">
<h1>tunning</h1>
<p>O Random Forest é um algorítmo que possui alguns parâmetros que podem ser otimizados em cada resample no intuito de otimizar alguma métrica, essa técnica é conhecida como tunning dos parâmetros.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1"></a><span class="co"># aumentando os folds para 10</span></span>
<span id="cb57-2"><a href="#cb57-2"></a><span class="kw">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb57-3"><a href="#cb57-3"></a>score_folds &lt;-<span class="st"> </span><span class="kw">vfold_cv</span>(train, <span class="dt">strata =</span> <span class="st">&quot;highest_education&quot;</span>, <span class="dt">v =</span> <span class="dv">10</span>)</span>
<span id="cb57-4"><a href="#cb57-4"></a></span>
<span id="cb57-5"><a href="#cb57-5"></a><span class="co"># tunning</span></span>
<span id="cb57-6"><a href="#cb57-6"></a>model_spec_rf_tune &lt;-<span class="st"> </span><span class="kw">rand_forest</span>(</span>
<span id="cb57-7"><a href="#cb57-7"></a>    <span class="dt">mode    =</span> <span class="st">&quot;regression&quot;</span>,</span>
<span id="cb57-8"><a href="#cb57-8"></a>    <span class="dt">mtry    =</span> <span class="kw">tune</span>(),</span>
<span id="cb57-9"><a href="#cb57-9"></a>    <span class="dt">trees   =</span> <span class="kw">tune</span>(),</span>
<span id="cb57-10"><a href="#cb57-10"></a>    <span class="dt">min_n   =</span> <span class="kw">tune</span>()</span>
<span id="cb57-11"><a href="#cb57-11"></a>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb57-12"><a href="#cb57-12"></a><span class="st">    </span><span class="kw">set_engine</span>(<span class="st">&quot;ranger&quot;</span>)</span>
<span id="cb57-13"><a href="#cb57-13"></a></span>
<span id="cb57-14"><a href="#cb57-14"></a></span>
<span id="cb57-15"><a href="#cb57-15"></a>wflw_spec_rf_tune &lt;-<span class="st"> </span><span class="kw">workflow</span>() <span class="op">%&gt;%</span></span>
<span id="cb57-16"><a href="#cb57-16"></a><span class="st">    </span><span class="kw">add_model</span>(model_spec_rf_tune) <span class="op">%&gt;%</span></span>
<span id="cb57-17"><a href="#cb57-17"></a><span class="st">    </span><span class="kw">add_recipe</span>(recipe_spec)</span>
<span id="cb57-18"><a href="#cb57-18"></a></span>
<span id="cb57-19"><a href="#cb57-19"></a><span class="co"># tuning</span></span>
<span id="cb57-20"><a href="#cb57-20"></a><span class="kw">library</span>(tictoc)</span>
<span id="cb57-21"><a href="#cb57-21"></a><span class="kw">tic</span>()</span>
<span id="cb57-22"><a href="#cb57-22"></a><span class="kw">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb57-23"><a href="#cb57-23"></a>tune_results_rf &lt;-<span class="st"> </span>wflw_spec_rf_tune <span class="op">%&gt;%</span></span>
<span id="cb57-24"><a href="#cb57-24"></a><span class="st">    </span><span class="kw">tune_grid</span>(</span>
<span id="cb57-25"><a href="#cb57-25"></a>        <span class="dt">resamples =</span> score_folds,</span>
<span id="cb57-26"><a href="#cb57-26"></a>        <span class="dt">grid      =</span> <span class="dv">5</span>,</span>
<span id="cb57-27"><a href="#cb57-27"></a>        <span class="dt">control   =</span> <span class="kw">control_grid</span>(<span class="dt">verbose =</span> <span class="ot">TRUE</span>, <span class="dt">allow_par =</span> <span class="ot">TRUE</span>)</span>
<span id="cb57-28"><a href="#cb57-28"></a>    )</span></code></pre></div>
<pre><code>## i Creating pre-processing data to finalize unknown parameter: mtry</code></pre>
<pre><code>## i Fold01: preprocessor 1/1</code></pre>
<pre><code>## ✓ Fold01: preprocessor 1/1</code></pre>
<pre><code>## i Fold01: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## ✓ Fold01: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## i Fold01: preprocessor 1/1, model 1/5 (predictions)</code></pre>
<pre><code>## i Fold01: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## ✓ Fold01: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## i Fold01: preprocessor 1/1, model 2/5 (predictions)</code></pre>
<pre><code>## i Fold01: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## ✓ Fold01: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## i Fold01: preprocessor 1/1, model 3/5 (predictions)</code></pre>
<pre><code>## i Fold01: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## ✓ Fold01: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## i Fold01: preprocessor 1/1, model 4/5 (predictions)</code></pre>
<pre><code>## i Fold01: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## ✓ Fold01: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## i Fold01: preprocessor 1/1, model 5/5 (predictions)</code></pre>
<pre><code>## i Fold02: preprocessor 1/1</code></pre>
<pre><code>## ✓ Fold02: preprocessor 1/1</code></pre>
<pre><code>## i Fold02: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## ✓ Fold02: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## i Fold02: preprocessor 1/1, model 1/5 (predictions)</code></pre>
<pre><code>## i Fold02: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## ✓ Fold02: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## i Fold02: preprocessor 1/1, model 2/5 (predictions)</code></pre>
<pre><code>## i Fold02: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## ✓ Fold02: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## i Fold02: preprocessor 1/1, model 3/5 (predictions)</code></pre>
<pre><code>## i Fold02: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## ✓ Fold02: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## i Fold02: preprocessor 1/1, model 4/5 (predictions)</code></pre>
<pre><code>## i Fold02: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## ✓ Fold02: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## i Fold02: preprocessor 1/1, model 5/5 (predictions)</code></pre>
<pre><code>## i Fold03: preprocessor 1/1</code></pre>
<pre><code>## ✓ Fold03: preprocessor 1/1</code></pre>
<pre><code>## i Fold03: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## ✓ Fold03: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## i Fold03: preprocessor 1/1, model 1/5 (predictions)</code></pre>
<pre><code>## i Fold03: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## ✓ Fold03: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## i Fold03: preprocessor 1/1, model 2/5 (predictions)</code></pre>
<pre><code>## i Fold03: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## ✓ Fold03: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## i Fold03: preprocessor 1/1, model 3/5 (predictions)</code></pre>
<pre><code>## i Fold03: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## ✓ Fold03: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## i Fold03: preprocessor 1/1, model 4/5 (predictions)</code></pre>
<pre><code>## i Fold03: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## ✓ Fold03: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## i Fold03: preprocessor 1/1, model 5/5 (predictions)</code></pre>
<pre><code>## i Fold04: preprocessor 1/1</code></pre>
<pre><code>## ✓ Fold04: preprocessor 1/1</code></pre>
<pre><code>## i Fold04: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## ✓ Fold04: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## i Fold04: preprocessor 1/1, model 1/5 (predictions)</code></pre>
<pre><code>## i Fold04: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## ✓ Fold04: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## i Fold04: preprocessor 1/1, model 2/5 (predictions)</code></pre>
<pre><code>## i Fold04: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## ✓ Fold04: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## i Fold04: preprocessor 1/1, model 3/5 (predictions)</code></pre>
<pre><code>## i Fold04: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## ✓ Fold04: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## i Fold04: preprocessor 1/1, model 4/5 (predictions)</code></pre>
<pre><code>## i Fold04: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## ✓ Fold04: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## i Fold04: preprocessor 1/1, model 5/5 (predictions)</code></pre>
<pre><code>## i Fold05: preprocessor 1/1</code></pre>
<pre><code>## ✓ Fold05: preprocessor 1/1</code></pre>
<pre><code>## i Fold05: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## ✓ Fold05: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## i Fold05: preprocessor 1/1, model 1/5 (predictions)</code></pre>
<pre><code>## i Fold05: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## ✓ Fold05: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## i Fold05: preprocessor 1/1, model 2/5 (predictions)</code></pre>
<pre><code>## i Fold05: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## ✓ Fold05: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## i Fold05: preprocessor 1/1, model 3/5 (predictions)</code></pre>
<pre><code>## i Fold05: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## ✓ Fold05: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## i Fold05: preprocessor 1/1, model 4/5 (predictions)</code></pre>
<pre><code>## i Fold05: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## ✓ Fold05: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## i Fold05: preprocessor 1/1, model 5/5 (predictions)</code></pre>
<pre><code>## i Fold06: preprocessor 1/1</code></pre>
<pre><code>## ✓ Fold06: preprocessor 1/1</code></pre>
<pre><code>## i Fold06: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## ✓ Fold06: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## i Fold06: preprocessor 1/1, model 1/5 (predictions)</code></pre>
<pre><code>## i Fold06: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## ✓ Fold06: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## i Fold06: preprocessor 1/1, model 2/5 (predictions)</code></pre>
<pre><code>## i Fold06: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## ✓ Fold06: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## i Fold06: preprocessor 1/1, model 3/5 (predictions)</code></pre>
<pre><code>## i Fold06: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## ✓ Fold06: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## i Fold06: preprocessor 1/1, model 4/5 (predictions)</code></pre>
<pre><code>## i Fold06: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## ✓ Fold06: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## i Fold06: preprocessor 1/1, model 5/5 (predictions)</code></pre>
<pre><code>## i Fold07: preprocessor 1/1</code></pre>
<pre><code>## ✓ Fold07: preprocessor 1/1</code></pre>
<pre><code>## i Fold07: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## ✓ Fold07: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## i Fold07: preprocessor 1/1, model 1/5 (predictions)</code></pre>
<pre><code>## i Fold07: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## ✓ Fold07: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## i Fold07: preprocessor 1/1, model 2/5 (predictions)</code></pre>
<pre><code>## i Fold07: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## ✓ Fold07: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## i Fold07: preprocessor 1/1, model 3/5 (predictions)</code></pre>
<pre><code>## i Fold07: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## ✓ Fold07: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## i Fold07: preprocessor 1/1, model 4/5 (predictions)</code></pre>
<pre><code>## i Fold07: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## ✓ Fold07: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## i Fold07: preprocessor 1/1, model 5/5 (predictions)</code></pre>
<pre><code>## i Fold08: preprocessor 1/1</code></pre>
<pre><code>## ✓ Fold08: preprocessor 1/1</code></pre>
<pre><code>## i Fold08: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## ✓ Fold08: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## i Fold08: preprocessor 1/1, model 1/5 (predictions)</code></pre>
<pre><code>## i Fold08: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## ✓ Fold08: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## i Fold08: preprocessor 1/1, model 2/5 (predictions)</code></pre>
<pre><code>## i Fold08: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## ✓ Fold08: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## i Fold08: preprocessor 1/1, model 3/5 (predictions)</code></pre>
<pre><code>## i Fold08: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## ✓ Fold08: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## i Fold08: preprocessor 1/1, model 4/5 (predictions)</code></pre>
<pre><code>## i Fold08: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## ✓ Fold08: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## i Fold08: preprocessor 1/1, model 5/5 (predictions)</code></pre>
<pre><code>## i Fold09: preprocessor 1/1</code></pre>
<pre><code>## ✓ Fold09: preprocessor 1/1</code></pre>
<pre><code>## i Fold09: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## ✓ Fold09: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## i Fold09: preprocessor 1/1, model 1/5 (predictions)</code></pre>
<pre><code>## i Fold09: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## ✓ Fold09: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## i Fold09: preprocessor 1/1, model 2/5 (predictions)</code></pre>
<pre><code>## i Fold09: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## ✓ Fold09: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## i Fold09: preprocessor 1/1, model 3/5 (predictions)</code></pre>
<pre><code>## i Fold09: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## ✓ Fold09: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## i Fold09: preprocessor 1/1, model 4/5 (predictions)</code></pre>
<pre><code>## i Fold09: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## ✓ Fold09: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## i Fold09: preprocessor 1/1, model 5/5 (predictions)</code></pre>
<pre><code>## i Fold10: preprocessor 1/1</code></pre>
<pre><code>## ✓ Fold10: preprocessor 1/1</code></pre>
<pre><code>## i Fold10: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## ✓ Fold10: preprocessor 1/1, model 1/5</code></pre>
<pre><code>## i Fold10: preprocessor 1/1, model 1/5 (predictions)</code></pre>
<pre><code>## i Fold10: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## ✓ Fold10: preprocessor 1/1, model 2/5</code></pre>
<pre><code>## i Fold10: preprocessor 1/1, model 2/5 (predictions)</code></pre>
<pre><code>## i Fold10: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## ✓ Fold10: preprocessor 1/1, model 3/5</code></pre>
<pre><code>## i Fold10: preprocessor 1/1, model 3/5 (predictions)</code></pre>
<pre><code>## i Fold10: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## ✓ Fold10: preprocessor 1/1, model 4/5</code></pre>
<pre><code>## i Fold10: preprocessor 1/1, model 4/5 (predictions)</code></pre>
<pre><code>## i Fold10: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## ✓ Fold10: preprocessor 1/1, model 5/5</code></pre>
<pre><code>## i Fold10: preprocessor 1/1, model 5/5 (predictions)</code></pre>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="#cb229-1"></a><span class="kw">toc</span>()</span></code></pre></div>
<pre><code>## 161.665 sec elapsed</code></pre>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="#cb231-1"></a>tune_results_rf <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">show_best</span>(<span class="dt">metric =</span> <span class="st">&quot;rsq&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 9
##    mtry trees min_n .metric .estimator   mean     n std_err .config             
##   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               
## 1     1   217    37 rsq     standard   0.0584    10 0.00452 Preprocessor1_Model4
## 2    12  1845    27 rsq     standard   0.0434    10 0.00602 Preprocessor1_Model1
## 3    10  1498     9 rsq     standard   0.0415    10 0.00560 Preprocessor1_Model5
## 4    20   863    20 rsq     standard   0.0397    10 0.00570 Preprocessor1_Model2
## 5    16   728    15 rsq     standard   0.0397    10 0.00569 Preprocessor1_Model3</code></pre>
<p>Acabamos aumentando os valores do RMSE. Ao final, nosso melhor modelo performou muito ruim, explicando minimamente a variância presente nos dados e com RMSE de aproximadamente 20. Realmente acredito que não tem muito a ser feito nesse modelo de regressão, pois precisamos de mais dados e mais variáveis.</p>
<p>Uma alternativa que proponho é a avaliação da performance dos estudantes utilizando um modelo de classificação e a variável de <code>final_result</code> para prever a probabilidade do estudante ser aprovado ou não.</p>
</div>
<div id="classification" class="section level1">
<h1>Classification</h1>
<p>Vamos ver então como se sai o modelo de classificação.</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="#cb233-1"></a>student_final_result_tbl &lt;-<span class="st"> </span>student_info <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb233-2"><a href="#cb233-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="kw">across</span>(<span class="kw">where</span>(is.character), as_factor)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb233-3"><a href="#cb233-3"></a><span class="st">  </span><span class="kw">drop_na</span>(imd_band) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb233-4"><a href="#cb233-4"></a><span class="st">  </span><span class="co"># ordem correta dos fatores</span></span>
<span id="cb233-5"><a href="#cb233-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">imd_band =</span> <span class="kw">fct_rev</span>(imd_band),</span>
<span id="cb233-6"><a href="#cb233-6"></a>         <span class="dt">age_band =</span> <span class="kw">fct_rev</span>(age_band)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb233-7"><a href="#cb233-7"></a><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>studied_credits) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb233-8"><a href="#cb233-8"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">imd_band =</span> <span class="kw">as.ordered</span>(imd_band))</span>
<span id="cb233-9"><a href="#cb233-9"></a></span>
<span id="cb233-10"><a href="#cb233-10"></a><span class="co"># visualizando as proporções depois do tratamento</span></span>
<span id="cb233-11"><a href="#cb233-11"></a>plot_all_full_trans &lt;-<span class="st"> </span><span class="cf">function</span>(<span class="dt">name =</span> <span class="st">&quot;region&quot;</span>) {</span>
<span id="cb233-12"><a href="#cb233-12"></a>  </span>
<span id="cb233-13"><a href="#cb233-13"></a>  student_final_result_tbl <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb233-14"><a href="#cb233-14"></a><span class="st">    </span><span class="kw">count</span>(.data[[name]]) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb233-15"><a href="#cb233-15"></a><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">prop =</span> n<span class="op">/</span><span class="kw">sum</span>(n)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb233-16"><a href="#cb233-16"></a><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> <span class="kw">fct_reorder</span>(.data[[name]], prop),</span>
<span id="cb233-17"><a href="#cb233-17"></a>               <span class="dt">x =</span> prop)) <span class="op">+</span></span>
<span id="cb233-18"><a href="#cb233-18"></a><span class="st">    </span><span class="kw">geom_col</span>()</span>
<span id="cb233-19"><a href="#cb233-19"></a>}</span>
<span id="cb233-20"><a href="#cb233-20"></a></span>
<span id="cb233-21"><a href="#cb233-21"></a>names &lt;-<span class="st"> </span><span class="kw">names</span>(student_final_result_tbl <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="kw">where</span>(is.factor)))</span>
<span id="cb233-22"><a href="#cb233-22"></a>all_plots &lt;-<span class="st"> </span><span class="kw">map</span>(names, plot_all_full_trans)</span>
<span id="cb233-23"><a href="#cb233-23"></a>cowplot<span class="op">::</span><span class="kw">plot_grid</span>(<span class="dt">plotlist =</span> all_plots)</span></code></pre></div>
<p><img src="etapa2_3_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Classes com valores muito baixos podem gerar problemas na hora das divisões entre treino e teste, por isso iremos agrupar algumas classes segundo descrição abaixo:</p>
<ul>
<li>age_band: vai passar a ter duas variáveis categóricas, de 0 a 35 anos e acima de 35 anos.</li>
<li>highest_education: vai passar a ter uma variável chamada “outros” oriunda da junção de <code>HE Qualification</code>, <code>No Formal quals</code> e <code>Post Graduate Qualification</code>.</li>
<li>final_result: <code>Withdrawn</code> e <code>Fail</code> serão consideradas como <code>Fail</code> e <code>Distinction</code> e <code>Pass</code> como <code>Pass</code>.</li>
</ul>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="#cb234-1"></a>student_final_result_v2_tbl &lt;-<span class="st"> </span>student_final_result_tbl <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb234-2"><a href="#cb234-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age_band =</span> <span class="kw">as.character</span>(age_band)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb234-3"><a href="#cb234-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age_band =</span> <span class="kw">case_when</span>(</span>
<span id="cb234-4"><a href="#cb234-4"></a>    age_band <span class="op">==</span><span class="st"> &quot;55&lt;=&quot;</span> <span class="op">~</span><span class="st"> &quot;35-55&quot;</span>,</span>
<span id="cb234-5"><a href="#cb234-5"></a>    <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span>age_band</span>
<span id="cb234-6"><a href="#cb234-6"></a>  )) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb234-7"><a href="#cb234-7"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age_band =</span> <span class="kw">case_when</span>(</span>
<span id="cb234-8"><a href="#cb234-8"></a>    age_band <span class="op">==</span><span class="st"> &quot;35-55&quot;</span> <span class="op">~</span><span class="st"> &quot;35&lt;=&quot;</span>,</span>
<span id="cb234-9"><a href="#cb234-9"></a>    <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span>age_band</span>
<span id="cb234-10"><a href="#cb234-10"></a>  )) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb234-11"><a href="#cb234-11"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age_band =</span> <span class="kw">factor</span>(age_band, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;0-35&quot;</span>, <span class="st">&quot;35&lt;=&quot;</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb234-12"><a href="#cb234-12"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age_band =</span> <span class="kw">as.ordered</span>(age_band)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb234-13"><a href="#cb234-13"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">highest_education =</span> <span class="kw">fct_lump</span>(highest_education, <span class="dt">prop =</span> <span class="fl">0.2</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb234-14"><a href="#cb234-14"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">highest_education =</span> <span class="kw">factor</span>(highest_education, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;Other&quot;</span>, <span class="st">&quot;Lower Than A Level&quot;</span>, <span class="st">&quot;A Level or Equivalent&quot;</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb234-15"><a href="#cb234-15"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">highest_education =</span> <span class="kw">as.ordered</span>(highest_education)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb234-16"><a href="#cb234-16"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">final_result =</span> final_result <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">as.character</span>()) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb234-17"><a href="#cb234-17"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">final_result =</span> <span class="kw">case_when</span>(</span>
<span id="cb234-18"><a href="#cb234-18"></a>    final_result <span class="op">==</span><span class="st"> &quot;Withdrawn&quot;</span> <span class="op">~</span><span class="st"> &quot;Fail&quot;</span>,</span>
<span id="cb234-19"><a href="#cb234-19"></a>    final_result <span class="op">==</span><span class="st"> &quot;Distinction&quot;</span> <span class="op">~</span><span class="st"> &quot;Pass&quot;</span>,</span>
<span id="cb234-20"><a href="#cb234-20"></a>    <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span>final_result</span>
<span id="cb234-21"><a href="#cb234-21"></a>  )) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb234-22"><a href="#cb234-22"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">final_result =</span> <span class="kw">as.factor</span>(final_result))</span></code></pre></div>
<p>Vamos visualizar nossas variáveis categóricas mais uma vez antes da modelagem.</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="#cb235-1"></a><span class="co"># visualizando as proporções</span></span>
<span id="cb235-2"><a href="#cb235-2"></a>plot_all_full_prepro &lt;-<span class="st"> </span><span class="cf">function</span>(<span class="dt">name =</span> <span class="st">&quot;region&quot;</span>) {</span>
<span id="cb235-3"><a href="#cb235-3"></a>  </span>
<span id="cb235-4"><a href="#cb235-4"></a>  student_final_result_v2_tbl <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb235-5"><a href="#cb235-5"></a><span class="st">    </span><span class="kw">count</span>(.data[[name]]) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb235-6"><a href="#cb235-6"></a><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">prop =</span> n<span class="op">/</span><span class="kw">sum</span>(n)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb235-7"><a href="#cb235-7"></a><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> <span class="kw">fct_reorder</span>(.data[[name]], prop),</span>
<span id="cb235-8"><a href="#cb235-8"></a>               <span class="dt">x =</span> prop)) <span class="op">+</span></span>
<span id="cb235-9"><a href="#cb235-9"></a><span class="st">    </span><span class="kw">geom_col</span>()</span>
<span id="cb235-10"><a href="#cb235-10"></a>}</span>
<span id="cb235-11"><a href="#cb235-11"></a></span>
<span id="cb235-12"><a href="#cb235-12"></a>names &lt;-<span class="st"> </span><span class="kw">names</span>(student_final_result_v2_tbl <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="kw">where</span>(is.factor)))</span>
<span id="cb235-13"><a href="#cb235-13"></a>all_plots &lt;-<span class="st"> </span><span class="kw">map</span>(names, plot_all_full_prepro)</span>
<span id="cb235-14"><a href="#cb235-14"></a>cowplot<span class="op">::</span><span class="kw">plot_grid</span>(<span class="dt">plotlist =</span> all_plots)</span></code></pre></div>
<p><img src="etapa2_3_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Pronto, nosso problema agora é uma classificação binomial e pronta modelagem. Vamos iniciar com os splits entre treino e teste.</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="#cb236-1"></a><span class="co"># split train and test</span></span>
<span id="cb236-2"><a href="#cb236-2"></a><span class="kw">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb236-3"><a href="#cb236-3"></a>splits &lt;-<span class="st"> </span><span class="kw">initial_split</span>(student_final_result_v2_tbl, <span class="dt">prop =</span> <span class="fl">.7</span>, <span class="dt">strata =</span> final_result)</span>
<span id="cb236-4"><a href="#cb236-4"></a></span>
<span id="cb236-5"><a href="#cb236-5"></a>train &lt;-<span class="st"> </span><span class="kw">training</span>(splits)</span>
<span id="cb236-6"><a href="#cb236-6"></a>test &lt;-<span class="st"> </span><span class="kw">testing</span>(splits)</span>
<span id="cb236-7"><a href="#cb236-7"></a></span>
<span id="cb236-8"><a href="#cb236-8"></a><span class="co"># recipe random forest</span></span>
<span id="cb236-9"><a href="#cb236-9"></a>recipe_class_rf_spec &lt;-<span class="st"> </span><span class="kw">recipe</span>(final_result <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> train) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb236-10"><a href="#cb236-10"></a><span class="st">  </span><span class="kw">update_role</span>(code_presentation, id_student, <span class="dt">new_role =</span> <span class="st">&quot;Identification&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb236-11"><a href="#cb236-11"></a><span class="st">  </span><span class="kw">step_dummy</span>(<span class="kw">all_predictors</span>(), <span class="op">-</span>num_of_prev_attempts, <span class="op">-</span>age_band, <span class="op">-</span>imd_band, <span class="op">-</span>highest_education)</span>
<span id="cb236-12"><a href="#cb236-12"></a>  </span>
<span id="cb236-13"><a href="#cb236-13"></a>recipe_class_rf_spec <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">prep</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">juice</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 22,038
## Columns: 27
## $ code_presentation           &lt;fct&gt; 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 20…
## $ id_student                  &lt;dbl&gt; 28400, 30268, 31604, 32885, 38053, 45462, 45642, 52130, 57506, 58873, 59185, 62155, 63400, 65002, 74372, 77…
## $ highest_education           &lt;ord&gt; Other, A Level or Equivalent, A Level or Equivalent, Lower Than A Level, A Level or Equivalent, Other, A Le…
## $ imd_band                    &lt;ord&gt; 20-30%, 30-40%, 50-60%, 50-60%, 80-90%, 30-40%, 90-100%, 70-80%, 70-80%, 20-30%, 60-70%, 50-60%, 40-50%, 70…
## $ age_band                    &lt;ord&gt; 35&lt;=, 35&lt;=, 35&lt;=, 0-35, 35&lt;=, 0-35, 0-35, 0-35, 35&lt;=, 0-35, 35&lt;=, 0-35, 35&lt;=, 0-35, 35&lt;=, 0-35, 35&lt;=, 0-35,…
## $ num_of_prev_attempts        &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ final_result                &lt;fct&gt; Pass, Fail, Pass, Pass, Pass, Pass, Pass, Pass, Pass, Pass, Pass, Pass, Pass, Fail, Fail, Pass, Fail, Pass,…
## $ code_module_Curso.B         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ code_module_Curso.C         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ code_module_Curso.D         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ code_module_Curso.E         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ code_module_Curso.F         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ code_module_Curso.G         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ gender_F                    &lt;dbl&gt; 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,…
## $ region_Scotland             &lt;dbl&gt; 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ region_North.Western.Region &lt;dbl&gt; 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ region_South.East.Region    &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,…
## $ region_West.Midlands.Region &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,…
## $ region_Wales                &lt;dbl&gt; 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ region_North.Region         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,…
## $ region_South.Region         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ region_Ireland              &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ region_South.West.Region    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,…
## $ region_East.Midlands.Region &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,…
## $ region_Yorkshire.Region     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ region_London.Region        &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ disability_Y                &lt;dbl&gt; 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,…</code></pre>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="#cb238-1"></a><span class="co"># recipe log regression</span></span>
<span id="cb238-2"><a href="#cb238-2"></a>recipe_class_logreg_spec &lt;-<span class="st"> </span><span class="kw">recipe</span>(final_result <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> train) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb238-3"><a href="#cb238-3"></a><span class="st">  </span><span class="kw">update_role</span>(code_presentation, id_student, <span class="dt">new_role =</span> <span class="st">&quot;Identification&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb238-4"><a href="#cb238-4"></a><span class="st">  </span><span class="kw">step_ordinalscore</span>(highest_education, imd_band, age_band) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb238-5"><a href="#cb238-5"></a><span class="st">  </span><span class="kw">step_dummy</span>(<span class="kw">all_predictors</span>(), <span class="op">-</span>num_of_prev_attempts, <span class="op">-</span>age_band, <span class="op">-</span>imd_band, <span class="op">-</span>highest_education)</span>
<span id="cb238-6"><a href="#cb238-6"></a></span>
<span id="cb238-7"><a href="#cb238-7"></a>recipe_class_logreg_spec <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">prep</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">juice</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 22,038
## Columns: 27
## $ code_presentation           &lt;fct&gt; 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 2013J, 20…
## $ id_student                  &lt;dbl&gt; 28400, 30268, 31604, 32885, 38053, 45462, 45642, 52130, 57506, 58873, 59185, 62155, 63400, 65002, 74372, 77…
## $ highest_education           &lt;dbl&gt; 1, 3, 3, 2, 3, 1, 3, 3, 2, 3, 2, 1, 2, 3, 3, 3, 2, 3, 2, 3, 1, 2, 1, 2, 1, 1, 3, 3, 3, 2, 3, 2, 2, 3, 3, 3,…
## $ imd_band                    &lt;dbl&gt; 9, 8, 7, 7, 6, 8, 10, 5, 5, 9, 4, 7, 3, 5, 2, 8, 5, 9, 6, 8, 4, 9, 10, 4, 4, 1, 3, 3, 7, 6, 10, 9, 10, 3, 8…
## $ age_band                    &lt;dbl&gt; 2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2,…
## $ num_of_prev_attempts        &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ final_result                &lt;fct&gt; Pass, Fail, Pass, Pass, Pass, Pass, Pass, Pass, Pass, Pass, Pass, Pass, Pass, Fail, Fail, Pass, Fail, Pass,…
## $ code_module_Curso.B         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ code_module_Curso.C         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ code_module_Curso.D         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ code_module_Curso.E         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ code_module_Curso.F         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ code_module_Curso.G         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ gender_F                    &lt;dbl&gt; 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,…
## $ region_Scotland             &lt;dbl&gt; 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ region_North.Western.Region &lt;dbl&gt; 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ region_South.East.Region    &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,…
## $ region_West.Midlands.Region &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,…
## $ region_Wales                &lt;dbl&gt; 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ region_North.Region         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,…
## $ region_South.Region         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ region_Ireland              &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ region_South.West.Region    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,…
## $ region_East.Midlands.Region &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,…
## $ region_Yorkshire.Region     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ region_London.Region        &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ disability_Y                &lt;dbl&gt; 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,…</code></pre>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="#cb240-1"></a><span class="co"># models</span></span>
<span id="cb240-2"><a href="#cb240-2"></a>model_lr &lt;-<span class="st"> </span><span class="kw">logistic_reg</span>(<span class="dt">mode =</span> <span class="st">&quot;classification&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb240-3"><a href="#cb240-3"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;glm&quot;</span>)</span>
<span id="cb240-4"><a href="#cb240-4"></a></span>
<span id="cb240-5"><a href="#cb240-5"></a><span class="co"># Os parâmetros escolhidos no random forest </span></span>
<span id="cb240-6"><a href="#cb240-6"></a><span class="co"># foram obtidos de uma etapa prévia de tunning</span></span>
<span id="cb240-7"><a href="#cb240-7"></a>model_rf &lt;-<span class="st"> </span><span class="kw">rand_forest</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb240-8"><a href="#cb240-8"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;ranger&quot;</span>, </span>
<span id="cb240-9"><a href="#cb240-9"></a>             <span class="dt">importance =</span> <span class="st">&quot;impurity&quot;</span>) <span class="op">%&gt;%</span><span class="st">  </span><span class="co"># variable importance</span></span>
<span id="cb240-10"><a href="#cb240-10"></a><span class="st">  </span><span class="kw">set_mode</span>(<span class="st">&quot;classification&quot;</span>)</span>
<span id="cb240-11"><a href="#cb240-11"></a></span>
<span id="cb240-12"><a href="#cb240-12"></a><span class="co"># workflow</span></span>
<span id="cb240-13"><a href="#cb240-13"></a>lr_wflow &lt;-<span class="st"> </span><span class="kw">workflow</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb240-14"><a href="#cb240-14"></a><span class="st">  </span><span class="kw">add_recipe</span>(recipe_class_logreg_spec) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb240-15"><a href="#cb240-15"></a><span class="st">  </span><span class="kw">add_model</span>(model_lr)</span>
<span id="cb240-16"><a href="#cb240-16"></a></span>
<span id="cb240-17"><a href="#cb240-17"></a>rf_wflow &lt;-<span class="st"> </span><span class="kw">workflow</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb240-18"><a href="#cb240-18"></a><span class="st">  </span><span class="kw">add_recipe</span>(recipe_class_rf_spec) <span class="op">%&gt;%</span></span>
<span id="cb240-19"><a href="#cb240-19"></a><span class="st">  </span><span class="kw">add_model</span>(model_rf) </span>
<span id="cb240-20"><a href="#cb240-20"></a></span>
<span id="cb240-21"><a href="#cb240-21"></a><span class="co"># treino</span></span>
<span id="cb240-22"><a href="#cb240-22"></a><span class="co"># treino do modelo com logistic regression</span></span>
<span id="cb240-23"><a href="#cb240-23"></a>model_log_fit &lt;-<span class="st"> </span>lr_wflow <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb240-24"><a href="#cb240-24"></a><span class="st">  </span><span class="kw">fit</span>(<span class="dt">data =</span> train)</span>
<span id="cb240-25"><a href="#cb240-25"></a></span>
<span id="cb240-26"><a href="#cb240-26"></a><span class="co"># treino do modelo com random forest</span></span>
<span id="cb240-27"><a href="#cb240-27"></a><span class="kw">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb240-28"><a href="#cb240-28"></a>model_rf_fit &lt;-<span class="st"> </span>rf_wflow <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb240-29"><a href="#cb240-29"></a><span class="st">  </span><span class="kw">fit</span>(<span class="dt">data =</span> train)</span>
<span id="cb240-30"><a href="#cb240-30"></a></span>
<span id="cb240-31"><a href="#cb240-31"></a><span class="co"># predições com o modelo treinado de logistic regression</span></span>
<span id="cb240-32"><a href="#cb240-32"></a>pred_lr &lt;-<span class="st"> </span><span class="kw">predict</span>(model_log_fit, test)</span>
<span id="cb240-33"><a href="#cb240-33"></a>pbp_pred_lr &lt;-<span class="st"> </span>pred_lr <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb240-34"><a href="#cb240-34"></a><span class="st">  </span><span class="kw">bind_cols</span>(test <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(final_result)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb240-35"><a href="#cb240-35"></a><span class="st">  </span><span class="co"># adicionando coluna com as probabilidades</span></span>
<span id="cb240-36"><a href="#cb240-36"></a><span class="st">  </span><span class="kw">bind_cols</span>(<span class="kw">predict</span>(model_log_fit, test, <span class="dt">type =</span> <span class="st">&quot;prob&quot;</span>))</span>
<span id="cb240-37"><a href="#cb240-37"></a></span>
<span id="cb240-38"><a href="#cb240-38"></a><span class="co"># predições com o modelo treinado de random forest</span></span>
<span id="cb240-39"><a href="#cb240-39"></a>pred_rf &lt;-<span class="st"> </span><span class="kw">predict</span>(model_rf_fit, test)</span>
<span id="cb240-40"><a href="#cb240-40"></a>pbp_pred_rf &lt;-<span class="st"> </span>pred_rf <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb240-41"><a href="#cb240-41"></a><span class="st">  </span><span class="kw">bind_cols</span>(test <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(final_result)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb240-42"><a href="#cb240-42"></a><span class="st">  </span><span class="co"># adicionando coluna com as probabilidades</span></span>
<span id="cb240-43"><a href="#cb240-43"></a><span class="st">  </span><span class="kw">bind_cols</span>(<span class="kw">predict</span>(model_rf_fit, test, <span class="dt">type =</span> <span class="st">&quot;prob&quot;</span>))</span>
<span id="cb240-44"><a href="#cb240-44"></a></span>
<span id="cb240-45"><a href="#cb240-45"></a><span class="co"># Random Forest -------------------------------------------------------</span></span>
<span id="cb240-46"><a href="#cb240-46"></a><span class="co"># acurácia e kap</span></span>
<span id="cb240-47"><a href="#cb240-47"></a>pbp_pred_rf <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb240-48"><a href="#cb240-48"></a><span class="st">  </span><span class="kw">metrics</span>(<span class="dt">truth =</span> final_result, </span>
<span id="cb240-49"><a href="#cb240-49"></a>          .pred_class)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   .metric  .estimator .estimate
##   &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
## 1 accuracy binary         0.603
## 2 kap      binary         0.196</code></pre>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="#cb242-1"></a><span class="co"># confusion matrix</span></span>
<span id="cb242-2"><a href="#cb242-2"></a>pbp_pred_rf <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb242-3"><a href="#cb242-3"></a><span class="st">  </span><span class="kw">conf_mat</span>(final_result, .pred_class)</span></code></pre></div>
<pre><code>##           Truth
## Prediction Fail Pass
##       Fail 3441 2141
##       Pass 1607 2255</code></pre>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="#cb244-1"></a><span class="co"># roc_auc</span></span>
<span id="cb244-2"><a href="#cb244-2"></a>pbp_pred_rf <span class="op">%&gt;%</span></span>
<span id="cb244-3"><a href="#cb244-3"></a><span class="st">  </span><span class="kw">roc_auc</span>(<span class="dt">truth =</span> final_result,</span>
<span id="cb244-4"><a href="#cb244-4"></a>          .pred_Pass)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 roc_auc binary         0.364</code></pre>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="#cb246-1"></a><span class="co"># Visualizando a roc_curve</span></span>
<span id="cb246-2"><a href="#cb246-2"></a>pbp_pred_rf <span class="op">%&gt;%</span></span>
<span id="cb246-3"><a href="#cb246-3"></a><span class="st">  </span><span class="kw">roc_curve</span>(<span class="dt">truth =</span> final_result,</span>
<span id="cb246-4"><a href="#cb246-4"></a>            .pred_Fail) <span class="op">%&gt;%</span></span>
<span id="cb246-5"><a href="#cb246-5"></a><span class="st">  </span><span class="kw">autoplot</span>()</span></code></pre></div>
<p><img src="etapa2_3_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="#cb247-1"></a><span class="co"># Log reg ----------------------</span></span>
<span id="cb247-2"><a href="#cb247-2"></a><span class="co"># acurácia e kap</span></span>
<span id="cb247-3"><a href="#cb247-3"></a>pbp_pred_lr <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb247-4"><a href="#cb247-4"></a><span class="st">  </span><span class="kw">metrics</span>(<span class="dt">truth =</span> final_result, </span>
<span id="cb247-5"><a href="#cb247-5"></a>          .pred_class)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   .metric  .estimator .estimate
##   &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
## 1 accuracy binary         0.585
## 2 kap      binary         0.158</code></pre>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="#cb249-1"></a><span class="co"># confusion matrix</span></span>
<span id="cb249-2"><a href="#cb249-2"></a>pbp_pred_lr <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb249-3"><a href="#cb249-3"></a><span class="st">  </span><span class="kw">conf_mat</span>(final_result, .pred_class)</span></code></pre></div>
<pre><code>##           Truth
## Prediction Fail Pass
##       Fail 3444 2311
##       Pass 1604 2085</code></pre>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="#cb251-1"></a><span class="co"># roc_auc</span></span>
<span id="cb251-2"><a href="#cb251-2"></a>pbp_pred_lr <span class="op">%&gt;%</span></span>
<span id="cb251-3"><a href="#cb251-3"></a><span class="st">  </span><span class="kw">roc_auc</span>(<span class="dt">truth =</span> final_result,</span>
<span id="cb251-4"><a href="#cb251-4"></a>          .pred_Pass)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 roc_auc binary         0.388</code></pre>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="#cb253-1"></a><span class="co"># Visualizando a roc_curve</span></span>
<span id="cb253-2"><a href="#cb253-2"></a>pbp_pred_lr <span class="op">%&gt;%</span></span>
<span id="cb253-3"><a href="#cb253-3"></a><span class="st">  </span><span class="kw">roc_curve</span>(<span class="dt">truth =</span> final_result,</span>
<span id="cb253-4"><a href="#cb253-4"></a>            .pred_Fail) <span class="op">%&gt;%</span></span>
<span id="cb253-5"><a href="#cb253-5"></a><span class="st">  </span><span class="kw">autoplot</span>()</span></code></pre></div>
<p><img src="etapa2_3_files/figure-html/unnamed-chunk-19-2.png" width="672" /></p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="#cb254-1"></a><span class="co"># estimate perfomance with cross validation</span></span>
<span id="cb254-2"><a href="#cb254-2"></a><span class="co"># set.seed(123)</span></span>
<span id="cb254-3"><a href="#cb254-3"></a><span class="co"># score_fold &lt;- vfold_cv(train, v = 5, strata = final_result)</span></span>
<span id="cb254-4"><a href="#cb254-4"></a><span class="co"># </span></span>
<span id="cb254-5"><a href="#cb254-5"></a><span class="co"># tune_xgb &lt;- boost_tree(</span></span>
<span id="cb254-6"><a href="#cb254-6"></a><span class="co">#   trees = 1000,</span></span>
<span id="cb254-7"><a href="#cb254-7"></a><span class="co">#   tree_depth = tune(), min_n = tune(),</span></span>
<span id="cb254-8"><a href="#cb254-8"></a><span class="co">#   loss_reduction = tune(),                     ## first three: model complexity</span></span>
<span id="cb254-9"><a href="#cb254-9"></a><span class="co">#   sample_size = tune(), mtry = tune(),         ## randomness</span></span>
<span id="cb254-10"><a href="#cb254-10"></a><span class="co">#   learn_rate = tune(),                         ## step size</span></span>
<span id="cb254-11"><a href="#cb254-11"></a><span class="co"># ) %&gt;%</span></span>
<span id="cb254-12"><a href="#cb254-12"></a><span class="co">#   set_engine(&quot;xgboost&quot;) %&gt;%</span></span>
<span id="cb254-13"><a href="#cb254-13"></a><span class="co">#   set_mode(&quot;classification&quot;)</span></span>
<span id="cb254-14"><a href="#cb254-14"></a><span class="co"># </span></span>
<span id="cb254-15"><a href="#cb254-15"></a><span class="co"># </span></span>
<span id="cb254-16"><a href="#cb254-16"></a><span class="co"># # Tunning Workflow -------------------------------------</span></span>
<span id="cb254-17"><a href="#cb254-17"></a><span class="co"># </span></span>
<span id="cb254-18"><a href="#cb254-18"></a><span class="co"># tune_xgb_wflw &lt;- workflow() %&gt;%</span></span>
<span id="cb254-19"><a href="#cb254-19"></a><span class="co">#   add_model(tune_xgb) %&gt;%</span></span>
<span id="cb254-20"><a href="#cb254-20"></a><span class="co">#   add_recipe(recipe_class_logreg_spec)</span></span>
<span id="cb254-21"><a href="#cb254-21"></a><span class="co"># </span></span>
<span id="cb254-22"><a href="#cb254-22"></a><span class="co"># </span></span>
<span id="cb254-23"><a href="#cb254-23"></a><span class="co"># # Tunning grid -----------------------------------------</span></span>
<span id="cb254-24"><a href="#cb254-24"></a><span class="co"># </span></span>
<span id="cb254-25"><a href="#cb254-25"></a><span class="co"># xgb_grid &lt;- grid_latin_hypercube(</span></span>
<span id="cb254-26"><a href="#cb254-26"></a><span class="co">#   tree_depth(),</span></span>
<span id="cb254-27"><a href="#cb254-27"></a><span class="co">#   min_n(),</span></span>
<span id="cb254-28"><a href="#cb254-28"></a><span class="co">#   loss_reduction(),</span></span>
<span id="cb254-29"><a href="#cb254-29"></a><span class="co">#   sample_size = sample_prop(),</span></span>
<span id="cb254-30"><a href="#cb254-30"></a><span class="co">#   finalize(mtry(), train),</span></span>
<span id="cb254-31"><a href="#cb254-31"></a><span class="co">#   learn_rate(),</span></span>
<span id="cb254-32"><a href="#cb254-32"></a><span class="co">#   size = 30</span></span>
<span id="cb254-33"><a href="#cb254-33"></a><span class="co"># )</span></span>
<span id="cb254-34"><a href="#cb254-34"></a><span class="co"># </span></span>
<span id="cb254-35"><a href="#cb254-35"></a><span class="co"># tictoc::tic()</span></span>
<span id="cb254-36"><a href="#cb254-36"></a><span class="co"># tune_res &lt;- tune_grid(</span></span>
<span id="cb254-37"><a href="#cb254-37"></a><span class="co">#   tune_xgb_wflw,</span></span>
<span id="cb254-38"><a href="#cb254-38"></a><span class="co">#   resamples = score_fold,</span></span>
<span id="cb254-39"><a href="#cb254-39"></a><span class="co">#   grid = xgb_grid, # 15 combos of model parameters</span></span>
<span id="cb254-40"><a href="#cb254-40"></a><span class="co">#   control = control_grid(verbose = TRUE, save_pred = TRUE),</span></span>
<span id="cb254-41"><a href="#cb254-41"></a><span class="co">#   metrics = metric_set(accuracy, kap, roc_auc)</span></span>
<span id="cb254-42"><a href="#cb254-42"></a><span class="co"># )</span></span>
<span id="cb254-43"><a href="#cb254-43"></a><span class="co"># tictoc::toc()</span></span>
<span id="cb254-44"><a href="#cb254-44"></a><span class="co"># </span></span>
<span id="cb254-45"><a href="#cb254-45"></a><span class="co"># best_fit_auc &lt;- select_best(tune_res, &quot;roc_auc&quot;)</span></span>
<span id="cb254-46"><a href="#cb254-46"></a><span class="co"># </span></span>
<span id="cb254-47"><a href="#cb254-47"></a><span class="co"># tune_res %&gt;% show_best(metric =&quot;roc_auc&quot;)</span></span>
<span id="cb254-48"><a href="#cb254-48"></a><span class="co"># </span></span>
<span id="cb254-49"><a href="#cb254-49"></a><span class="co"># # Finalizando com o melhor modelo do tunning</span></span>
<span id="cb254-50"><a href="#cb254-50"></a><span class="co"># final_xgb &lt;- finalize_workflow(</span></span>
<span id="cb254-51"><a href="#cb254-51"></a><span class="co">#   tune_xgb_wflw,</span></span>
<span id="cb254-52"><a href="#cb254-52"></a><span class="co">#   best_fit_auc</span></span>
<span id="cb254-53"><a href="#cb254-53"></a><span class="co"># )</span></span>
<span id="cb254-54"><a href="#cb254-54"></a><span class="co"># </span></span>
<span id="cb254-55"><a href="#cb254-55"></a><span class="co"># # treino</span></span>
<span id="cb254-56"><a href="#cb254-56"></a><span class="co"># # treino do modelo com logistic regression</span></span>
<span id="cb254-57"><a href="#cb254-57"></a><span class="co"># model_xgb_best_fit &lt;- final_xgb %&gt;% </span></span>
<span id="cb254-58"><a href="#cb254-58"></a><span class="co">#   fit(data = train)</span></span>
<span id="cb254-59"><a href="#cb254-59"></a><span class="co"># </span></span>
<span id="cb254-60"><a href="#cb254-60"></a><span class="co"># saveRDS(model_xgb_best_fit, &quot;model_xgb_best_fit.rds&quot;)</span></span>
<span id="cb254-61"><a href="#cb254-61"></a></span>
<span id="cb254-62"><a href="#cb254-62"></a>model_xgb_best_fit &lt;-<span class="st"> </span><span class="kw">readRDS</span>(<span class="st">&quot;model_xgb_best_fit.rds&quot;</span>)</span>
<span id="cb254-63"><a href="#cb254-63"></a></span>
<span id="cb254-64"><a href="#cb254-64"></a><span class="co"># predições com o modelo treinado de logistic regression</span></span>
<span id="cb254-65"><a href="#cb254-65"></a>pred_xgb &lt;-<span class="st"> </span><span class="kw">predict</span>(model_xgb_best_fit, test)</span>
<span id="cb254-66"><a href="#cb254-66"></a>pbp_pred_xg &lt;-<span class="st"> </span>pred_xgb <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb254-67"><a href="#cb254-67"></a><span class="st">  </span><span class="kw">bind_cols</span>(test <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(final_result)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb254-68"><a href="#cb254-68"></a><span class="st">  </span><span class="co"># adicionando coluna com as probabilidades</span></span>
<span id="cb254-69"><a href="#cb254-69"></a><span class="st">  </span><span class="kw">bind_cols</span>(<span class="kw">predict</span>(model_xgb_best_fit, test, <span class="dt">type =</span> <span class="st">&quot;prob&quot;</span>))</span>
<span id="cb254-70"><a href="#cb254-70"></a></span>
<span id="cb254-71"><a href="#cb254-71"></a><span class="co"># xgb -------------------------------------------------------</span></span>
<span id="cb254-72"><a href="#cb254-72"></a><span class="co"># acurácia e kap</span></span>
<span id="cb254-73"><a href="#cb254-73"></a>pbp_pred_xg <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb254-74"><a href="#cb254-74"></a><span class="st">  </span><span class="kw">metrics</span>(<span class="dt">truth =</span> final_result, </span>
<span id="cb254-75"><a href="#cb254-75"></a>          .pred_class)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   .metric  .estimator .estimate
##   &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
## 1 accuracy binary         0.613
## 2 kap      binary         0.216</code></pre>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb256-1"><a href="#cb256-1"></a><span class="co"># confusion matrix</span></span>
<span id="cb256-2"><a href="#cb256-2"></a>pbp_pred_xg <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb256-3"><a href="#cb256-3"></a><span class="st">  </span><span class="kw">conf_mat</span>(final_result, .pred_class)</span></code></pre></div>
<pre><code>##           Truth
## Prediction Fail Pass
##       Fail 3487 2094
##       Pass 1561 2302</code></pre>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="#cb258-1"></a><span class="co"># roc_auc</span></span>
<span id="cb258-2"><a href="#cb258-2"></a>pbp_pred_xg <span class="op">%&gt;%</span></span>
<span id="cb258-3"><a href="#cb258-3"></a><span class="st">  </span><span class="kw">roc_auc</span>(<span class="dt">truth =</span> final_result,</span>
<span id="cb258-4"><a href="#cb258-4"></a>          .pred_Fail)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 roc_auc binary         0.647</code></pre>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="#cb260-1"></a><span class="co"># Visualizando a roc_curve</span></span>
<span id="cb260-2"><a href="#cb260-2"></a>pbp_pred_xg <span class="op">%&gt;%</span></span>
<span id="cb260-3"><a href="#cb260-3"></a><span class="st">  </span><span class="kw">roc_curve</span>(<span class="dt">truth =</span> final_result,</span>
<span id="cb260-4"><a href="#cb260-4"></a>            .pred_Fail) <span class="op">%&gt;%</span></span>
<span id="cb260-5"><a href="#cb260-5"></a><span class="st">  </span><span class="kw">autoplot</span>()</span></code></pre></div>
<p><img src="etapa2_3_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="#cb261-1"></a><span class="co"># random forest -------------------</span></span>
<span id="cb261-2"><a href="#cb261-2"></a></span>
<span id="cb261-3"><a href="#cb261-3"></a><span class="co"># rf_tuning_spec &lt;- rand_forest(</span></span>
<span id="cb261-4"><a href="#cb261-4"></a><span class="co">#   mtry = tune(),</span></span>
<span id="cb261-5"><a href="#cb261-5"></a><span class="co">#   trees = 1000,</span></span>
<span id="cb261-6"><a href="#cb261-6"></a><span class="co">#   min_n = tune()</span></span>
<span id="cb261-7"><a href="#cb261-7"></a><span class="co"># ) %&gt;%</span></span>
<span id="cb261-8"><a href="#cb261-8"></a><span class="co">#   set_mode(&quot;classification&quot;) %&gt;%</span></span>
<span id="cb261-9"><a href="#cb261-9"></a><span class="co">#   set_engine(&quot;ranger&quot;)  </span></span>
<span id="cb261-10"><a href="#cb261-10"></a><span class="co"># </span></span>
<span id="cb261-11"><a href="#cb261-11"></a><span class="co"># tune_rf_wf &lt;- workflow() %&gt;%</span></span>
<span id="cb261-12"><a href="#cb261-12"></a><span class="co">#   add_model(rf_tuning_spec) %&gt;%</span></span>
<span id="cb261-13"><a href="#cb261-13"></a><span class="co">#   add_recipe(recipe_class_spec)</span></span>
<span id="cb261-14"><a href="#cb261-14"></a><span class="co"># </span></span>
<span id="cb261-15"><a href="#cb261-15"></a><span class="co"># tictoc::tic()</span></span>
<span id="cb261-16"><a href="#cb261-16"></a><span class="co"># tune_res &lt;- tune_grid(</span></span>
<span id="cb261-17"><a href="#cb261-17"></a><span class="co">#   tune_rf_wf,</span></span>
<span id="cb261-18"><a href="#cb261-18"></a><span class="co">#   resamples = score_fold,</span></span>
<span id="cb261-19"><a href="#cb261-19"></a><span class="co">#   grid = 10, # 15 combos of model parameters</span></span>
<span id="cb261-20"><a href="#cb261-20"></a><span class="co">#   control = control_grid(verbose = TRUE, save_pred = TRUE),</span></span>
<span id="cb261-21"><a href="#cb261-21"></a><span class="co">#   metrics = metric_set(accuracy, kap, roc_auc)</span></span>
<span id="cb261-22"><a href="#cb261-22"></a><span class="co"># )</span></span>
<span id="cb261-23"><a href="#cb261-23"></a><span class="co"># tictoc::toc()</span></span>
<span id="cb261-24"><a href="#cb261-24"></a><span class="co"># </span></span>
<span id="cb261-25"><a href="#cb261-25"></a><span class="co"># best_fit_auc &lt;- select_best(tune_res, &quot;roc_auc&quot;)</span></span>
<span id="cb261-26"><a href="#cb261-26"></a><span class="co"># </span></span>
<span id="cb261-27"><a href="#cb261-27"></a><span class="co"># tune_res %&gt;% show_best(metric =&quot;roc_auc&quot;)</span></span>
<span id="cb261-28"><a href="#cb261-28"></a><span class="co"># </span></span>
<span id="cb261-29"><a href="#cb261-29"></a><span class="co"># # Finalizando com o melhor modelo do tunning</span></span>
<span id="cb261-30"><a href="#cb261-30"></a><span class="co"># final_rf &lt;- finalize_workflow(</span></span>
<span id="cb261-31"><a href="#cb261-31"></a><span class="co">#   tune_rf_wf,</span></span>
<span id="cb261-32"><a href="#cb261-32"></a><span class="co">#   best_fit_auc</span></span>
<span id="cb261-33"><a href="#cb261-33"></a><span class="co"># )</span></span>
<span id="cb261-34"><a href="#cb261-34"></a><span class="co"># </span></span>
<span id="cb261-35"><a href="#cb261-35"></a><span class="co"># saveRDS(final_rf, &quot;final_rf.rds&quot;)</span></span>
<span id="cb261-36"><a href="#cb261-36"></a></span>
<span id="cb261-37"><a href="#cb261-37"></a>final_rf &lt;-<span class="st"> </span><span class="kw">readRDS</span>(<span class="st">&quot;final_rf.rds&quot;</span>)</span>
<span id="cb261-38"><a href="#cb261-38"></a></span>
<span id="cb261-39"><a href="#cb261-39"></a><span class="co"># Finalizando com o melhor modelo do tunning</span></span>
<span id="cb261-40"><a href="#cb261-40"></a>final_rf &lt;-<span class="st"> </span><span class="kw">finalize_workflow</span>(</span>
<span id="cb261-41"><a href="#cb261-41"></a>  tune_rf_wf,</span>
<span id="cb261-42"><a href="#cb261-42"></a>  best_fit_auc</span>
<span id="cb261-43"><a href="#cb261-43"></a>)</span>
<span id="cb261-44"><a href="#cb261-44"></a></span>
<span id="cb261-45"><a href="#cb261-45"></a></span>
<span id="cb261-46"><a href="#cb261-46"></a><span class="co"># # Como nós precisamos fazer alterações nos dados de teste</span></span>
<span id="cb261-47"><a href="#cb261-47"></a><span class="co"># # que estão fora da receita de pré-processamento (recipe)</span></span>
<span id="cb261-48"><a href="#cb261-48"></a><span class="co"># # não poderemos utilizar o last_fit(), e por isso</span></span>
<span id="cb261-49"><a href="#cb261-49"></a><span class="co"># # o re-treino com o melhor modelo foi feito manualmente.</span></span>
<span id="cb261-50"><a href="#cb261-50"></a><span class="co"># </span></span>
<span id="cb261-51"><a href="#cb261-51"></a><span class="co"># </span></span>
<span id="cb261-52"><a href="#cb261-52"></a><span class="co"># Treino com o melhor modelo de xgboost --------------------------------------</span></span>
<span id="cb261-53"><a href="#cb261-53"></a></span>
<span id="cb261-54"><a href="#cb261-54"></a>model_rf_best_fit &lt;-<span class="st"> </span>final_rf <span class="op">%&gt;%</span></span>
<span id="cb261-55"><a href="#cb261-55"></a><span class="st">  </span><span class="kw">fit</span>(<span class="dt">data =</span> train)</span>
<span id="cb261-56"><a href="#cb261-56"></a></span>
<span id="cb261-57"><a href="#cb261-57"></a><span class="co">## Previsões com o melhor modelo de xgboost ----------------------------------</span></span>
<span id="cb261-58"><a href="#cb261-58"></a></span>
<span id="cb261-59"><a href="#cb261-59"></a>pred_rf &lt;-<span class="st"> </span><span class="kw">predict</span>(model_rf_best_fit, test)</span>
<span id="cb261-60"><a href="#cb261-60"></a>pbp_pred_rf &lt;-<span class="st"> </span>pred_rf <span class="op">%&gt;%</span></span>
<span id="cb261-61"><a href="#cb261-61"></a><span class="st">  </span><span class="kw">bind_cols</span>(test <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(final_result)) <span class="op">%&gt;%</span></span>
<span id="cb261-62"><a href="#cb261-62"></a><span class="st">  </span><span class="kw">bind_cols</span>(<span class="kw">predict</span>(model_rf_best_fit, test, <span class="dt">type =</span> <span class="st">&quot;prob&quot;</span>))</span>
<span id="cb261-63"><a href="#cb261-63"></a></span>
<span id="cb261-64"><a href="#cb261-64"></a><span class="co">## Métricas do melhor modelo de xgboost --------------------------------------</span></span>
<span id="cb261-65"><a href="#cb261-65"></a><span class="co"># acurácia e kap</span></span>
<span id="cb261-66"><a href="#cb261-66"></a>pbp_pred_rf <span class="op">%&gt;%</span></span>
<span id="cb261-67"><a href="#cb261-67"></a><span class="st">  </span><span class="kw">metrics</span>(<span class="dt">truth =</span> final_result,</span>
<span id="cb261-68"><a href="#cb261-68"></a>          .pred_class)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   .metric  .estimator .estimate
##   &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
## 1 accuracy binary         0.605
## 2 kap      binary         0.198</code></pre>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="#cb263-1"></a><span class="co"># confusion matrix</span></span>
<span id="cb263-2"><a href="#cb263-2"></a>pbp_pred_rf <span class="op">%&gt;%</span></span>
<span id="cb263-3"><a href="#cb263-3"></a><span class="st">  </span><span class="kw">conf_mat</span>(final_result, .pred_class)</span></code></pre></div>
<pre><code>##           Truth
## Prediction Fail Pass
##       Fail 3521 2205
##       Pass 1527 2191</code></pre>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="#cb265-1"></a><span class="co"># Visualizando a roc_curve</span></span>
<span id="cb265-2"><a href="#cb265-2"></a>pbp_pred_rf <span class="op">%&gt;%</span></span>
<span id="cb265-3"><a href="#cb265-3"></a><span class="st">  </span><span class="kw">roc_curve</span>(<span class="dt">truth =</span> final_result,</span>
<span id="cb265-4"><a href="#cb265-4"></a>            .pred_Fail) <span class="op">%&gt;%</span></span>
<span id="cb265-5"><a href="#cb265-5"></a><span class="st">  </span><span class="kw">autoplot</span>()</span></code></pre></div>
<p><img src="etapa2_3_files/figure-html/unnamed-chunk-20-2.png" width="672" /></p>
<p>Importância das variáveis. Para regressão logistica converter para numérico</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="#cb266-1"></a><span class="kw">library</span>(vip)</span>
<span id="cb266-2"><a href="#cb266-2"></a><span class="co"># logistic_regression</span></span>
<span id="cb266-3"><a href="#cb266-3"></a>g1 &lt;-<span class="st"> </span>model_xgb_best_fit <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb266-4"><a href="#cb266-4"></a><span class="st">  </span><span class="kw">pull_workflow_fit</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb266-5"><a href="#cb266-5"></a><span class="st">  </span><span class="kw">vip</span>(<span class="dt">num_features =</span> <span class="dv">10</span>) <span class="op">+</span></span>
<span id="cb266-6"><a href="#cb266-6"></a><span class="st">  </span><span class="kw">geom_col</span>(<span class="dt">fill =</span> <span class="st">&quot;#2A43DE&quot;</span>) <span class="op">+</span></span>
<span id="cb266-7"><a href="#cb266-7"></a><span class="st">  </span><span class="kw">theme_minimal</span>() <span class="op">+</span></span>
<span id="cb266-8"><a href="#cb266-8"></a><span class="st">  </span><span class="kw">labs</span>(</span>
<span id="cb266-9"><a href="#cb266-9"></a>    <span class="dt">title =</span> <span class="st">&quot;Variáveis mais importantes </span><span class="ch">\n</span><span class="st">para o modelo de Logistic Regression&quot;</span></span>
<span id="cb266-10"><a href="#cb266-10"></a>  )</span>
<span id="cb266-11"><a href="#cb266-11"></a></span>
<span id="cb266-12"><a href="#cb266-12"></a>g1 &lt;-<span class="st"> </span>model_log_fit <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb266-13"><a href="#cb266-13"></a><span class="st">  </span><span class="kw">pull_workflow_fit</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb266-14"><a href="#cb266-14"></a><span class="st">  </span><span class="kw">vip</span>(<span class="dt">num_features =</span> <span class="dv">10</span>) <span class="op">+</span></span>
<span id="cb266-15"><a href="#cb266-15"></a><span class="st">  </span><span class="kw">geom_col</span>(<span class="dt">fill =</span> <span class="st">&quot;#2A43DE&quot;</span>) <span class="op">+</span></span>
<span id="cb266-16"><a href="#cb266-16"></a><span class="st">  </span><span class="kw">theme_minimal</span>() <span class="op">+</span></span>
<span id="cb266-17"><a href="#cb266-17"></a><span class="st">  </span><span class="kw">labs</span>(</span>
<span id="cb266-18"><a href="#cb266-18"></a>    <span class="dt">title =</span> <span class="st">&quot;Variáveis mais importantes </span><span class="ch">\n</span><span class="st">para o modelo de Logistic Regression&quot;</span></span>
<span id="cb266-19"><a href="#cb266-19"></a>  )</span></code></pre></div>
</div>
<div id="feature-engineering" class="section level1">
<h1>Feature Engineering</h1>
<p>Adição de novas features:</p>
<ul>
<li>taxa de reprovação</li>
<li>taxa de aprovação</li>
<li>quantidade de material de consulta</li>
<li>taxa de click na plataforma</li>
</ul>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
